language: node_js

node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ~/.cache/Cypress
    - ~/e2e/.npm
    - ~/e2e/.cache
    - ~/e2e/.cache/Cypress

install:
  - npm ci

jobs:
  include:
    - stage: validate
      script:
      - npm run validate
      - stage: test
      script:
      - ls
      - cd e2e
      - npm ci
      - npm run build
      - npm run test:e2e

